isucon_servers:
  hosts:
    isu_bench:
      ansible_host: isu_bench
    isu_1:
      ansible_host: isu_1
    isu_2:
      ansible_host: isu_2
    isu_3:
      ansible_host: isu_3
  vars:
    ansible_user: isucon
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    local_deploy_private_key_path: ~/.ssh/isucon-xxxxxxxxx
    local_deploy_public_key_path: ~/.ssh/isucon-xxxxxxxxx.pub
    git_repo_url: "git@github.com:faildb/isucon-xxxxxxxx.git"
