isucon_servers:
  hosts:
    isu_1:
      ansible_host: 3.112.73.234
  #    isu_2:
  #      ansible_host: 35.72.211.142
  #    isu_3:
  #      ansible_host: 35.72.211.142
  vars:
    ansible_user: isucon
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    local_deploy_private_key_path: ~/.ssh/isucon11-final-taki-suburi-20220908
    local_deploy_public_key_path: ~/.ssh/isucon11-final-taki-suburi-20220908.pub
